### ISSUE TITLE
Windows Wallet compilation

### ISSUE THREAD

**Issue by xoma11** [z-classic/zclassic#102]
Hey!
Sha256 problem again.

+++ readlink -f ./zcutil/build-win.sh
++ dirname /home/mikhail/zclassic/zcutil/build-win.sh
+ cd /home/mikhail/zclassic/zcutil/..
+ cd depends/
+ make HOST=x86_64-w64-mingw32 V=1 NO_QT=1
Checksum missing or mismatched for rust source. Forcing re-download.
mkdir -p /home/mikhail/zclassic/depends/sources/download-stamps /home/mikhail/zclassic/depends/sources
rm -f /home/mikhail/zclassic/depends/sources/download-stamps/.stamp_fetched-rust-.hash
touch /home/mikhail/zclassic/depends/sources/download-stamps/.stamp_fetched-rust-.hash
cd /home/mikhail/zclassic/depends/sources/download-stamps; (test -f /home/mikhail/zclassic/depends/sources/ || ( mkdir -p /home/mikhail/zclassic/depends/work/download/rust-1.16.0 && echo Fetching rust... && ( wget --timeout=10 --tries=3 -nv -O "/home/mikhail/zclassic/depends/work/download/rust-1.16.0/.temp" "https://z.cash/depends-sources/" || wget --timeout=10 --tries=3 -nv -O "/home/mikhail/zclassic/depends/work/download/rust-1.16.0/.temp" "https://z.cash/depends-sources/" ) && echo "  /home/mikhail/zclassic/depends/work/download/rust-1.16.0/.temp" > /home/mikhail/zclassic/depends/work/download/rust-1.16.0/..hash && sha256sum -c /home/mikhail/zclassic/depends/work/download/rust-1.16.0/..hash && mv /home/mikhail/zclassic/depends/work/download/rust-1.16.0/.temp /home/mikhail/zclassic/depends/sources/ && rm -rf /home/mikhail/zclassic/depends/work/download/rust-1.16.0 ))
Fetching rust...
2017-09-14 14:58:46 URL:https://z.cash/depends-sources/ [7520] -> "/home/mikhail/zclassic/depends/work/download/rust-1.16.0/.temp" [1]
sha256sum: /home/mikhail/zclassic/depends/work/download/rust-1.16.0/..hash: no properly formatted SHA256 checksum lines found
funcs.mk:242: recipe for target '/home/mikhail/zclassic/depends/sources/download-stamps/.stamp_fetched-rust-.hash' failed
make: *** [/home/mikhail/zclassic/depends/sources/download-stamps/.stamp_fetched-rust-.hash] Error 1
+ ./autogen.sh

+++ readlink -f ./zcutil/build-win.sh
++ dirname /home/mikhail/zclassic/zcutil/build-win.sh
+ cd /home/mikhail/zclassic/zcutil/..
+ cd depends/
+ make HOST=x86_64-w64-mingw32 V=1 NO_QT=1
echo Extracting rust...
Extracting rust...
mkdir -p /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88
cd /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88; mkdir -p /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88 && echo "  /home/mikhail/zclassic/depends/sources/" > /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88/..hash &&  sha256sum -c /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88/..hash && tar --strip-components=1 -xf /home/mikhail/zclassic/depends/sources/
sha256sum: /home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88/..hash: no properly formatted SHA256 checksum lines found
funcs.mk:242: recipe for target '/home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88/.stamp_extracted' failed
make: *** [/home/mikhail/zclassic/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-e663dba3e88/.stamp_extracted] Error 1
+ ./autogen.sh
OS ubuntu 16.04(and test ubuntu 17.06)
CPU Xeon
Ram 36 GB
HDD 3.5 TB

Whats a problem?

**Comment by aayanl** [comment]
Should be fixed now

**Comment by Tomas-M** [comment]
I downloaded zcash sources and I am trying to cross compile it for Windows on Ubuntu 16. I know this is not your problem, but I am using zclassic's build script, by running

    ./zcutil/build-win.sh --disable-tests --disable-mining --disable-rust

I had to add NO_RUST=1 to the line which starts with "cd depends/ ..." in order for the dependencies to compile properly, else it tried to compile rust which brought some errors, and since I can see there is no need for the rust at all, disabling it this way fixed my issue. So maybe you may consider adding NO_RUST=1 there for zclassic too.

The next line (autogen.sh) completes properly as well, and the next few lines afterwards are OK too.

But the last line (make) fails for me. I would like to kindly ask you for information. Is the source code of zclassic patched in any significant way to make it cross-compile using your script? Because pure zcash sources cannot be compiled with it. I get following error:

    crypto/equihash.cpp: In member function 'int Equihash<N, K>::InitialiseState(eh_HashState&)':
    crypto/equihash.cpp:33:30: error: there are no arguments to 'htole32' that depend on a template parameter, so a declaration of 'htole32' must be available [-fpermissive]
         uint32_t le_N = htole32(N);
                                  ^
    crypto/equihash.cpp:33:30: note: (if you use '-fpermissive', G++ will accept your code, but allowing the 
use of an undeclared name is deprecated)

(adding -fpermissive to cflags won't help).

Or is it perhaps a problem in my environment configuration?
Thank you

**Comment by Tomas-M** [comment]
Never mind I just figured it out. I can see zclassic has lots of patches for this purpose to be able to build for windows.
