### ISSUE TITLE
Unable to synchronize to block data

### ISSUE THREAD

**Issue by dacelee** [z-classic/zclassic#190]
zclassic.conf
addnode=electrum.zclassicblue.org
addnode=dnsseed.rotorproject.org
rpcuser=username
rpcpassword=lK/k6bX9iBM

More than 2 days

Downloading blocks 0

**Comment by dacelee** [comment]
help me

**Comment by VictorLux** [comment]
Please try 
addnode=electrum.zclassic.community
addnode=zclele.duckdns.org

**Comment by nimbosa** [comment]
@dacelee 

1. what version are you using? it must be very old because recent releases use zcld and not zcashd anymore as the name of the binary? and,

2. is this on Linux, Mac or Windows?

anyway, this a stale issue and should have been resolved by now, if you need further help, please reach out on discord: https://discord.gg/45NNrMJ

Thanks!
